site_name: SOS Vitis
site_url: https://sosvitis.pages.dev
repo_name: hdiogosilva/sos-vitis
repo_url: https://github.com/hdiogosilva/sos-vitis
strict: true
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
extra_css:
- stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - mermaid2
nav:
    - 'Enquadramento': '/'
    - 'Hackathon':
        - 'Desafios':
            - 'Desafio 1': 'Hackathon/Desafios/desafio1.md'
            - 'Desafio 2': 'Hackathon/Desafios/desafio2.md'
            - 'Desafio 3': 'Hackathon/Desafios/desafio3.md'
        - 'Abordagem & Metodologia': 'Hackathon/metodologia.md'
        - 'Progresso': 'Hackathon/progresso.md'
        - 'Siglas': 'Hackathon/siglas.md'
        - 'Licença': 'Hackathon/licença.md'
    - 'Docs. de Trabalho':
        - 'Processos': 'DocsTrabalho/processos.md'
        - 'Modelo de Dados': 'DocsTrabalho/modelo-dados.md'
    - 'Desafio 1':
        - 'Resumo': 'Desafio 1/resumo.md'
        - 'Processo Atual': 'Desafio 1/processo-atual.md'
        - 'Novos Processos': 'Desafio 1/novos-processos.md'
        - 'Recomendações': 'Desafio 1/recomendacoes.md'
        - 'Modelo de Dados': 'Desafio 1/modelo-dados.md'
    - 'Desafio 2':
        - 'Resumo': 'Desafio 2/resumo.md'
        - 'Processo Atual': 'Desafio 2/processo-atual.md'
        - 'Novos Processos': 'Desafio 2/novos-processos.md'
    - 'Desafio 3':
        - 'Resumo': 'Desafio 3/resumo.md'
        - 'Novos Processos': 'Desafio 3/novos-processos.md'
