site_name: SOS Vitis
site_url: https://sosvitis.pages.dev
repo_name: hdiogosilva/sos-vitis
repo_url: https://github.com/hdiogosilva/sos-vitis
strict: true
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
extra_css:
- stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - mermaid2
